// Generated by Wrangler
declare namespace Cloudflare {
	interface Env {
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").ArenaMCP>;
		ARENA_API_BASE: string;
	}
}
interface Env extends Cloudflare.Env {}
